{% set data = load_setup_py_data() %}

package:
  name: read5
  version: {{ data['version'] }}

source:
  path: ../

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python>=3.8
    - pip
    - setuptools
  run:
    - python>=3.8
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

# TODO: Activate tests when pod5 is available via conda!
# test:
#   source_files:
#     - tests
#   requires:
#     - pytest
#     - pytest-cov
#   commands:
#     - pytest

about:
  home: {{ data['url'] }}
  summary: Wrapper to read fast5, slow5, blow5 and pod5 files.
  license: {{ data['license'] }}
  license_file: LICENSE
  doc_url: https://github.com/JannesSP/read5.github.io
  dev_url: {{ data['url'] }}