{% set data = load_setup_py_data() %}

package:
  name: read5
  version: {{ data['version'] }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -v .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyslow5 >=1.0
    - numpy >=1.20
    - h5py >=3.8
    - ont_vbz_hdf_plugin >=1.0
    # - pod5 >=0.2.3 # currently not available in conda

test:
  source_files:
    - tests
  imports:
    - read5
  requires:
    - pytest
  commands:
    - pip install pod5
    - pytest

about:
  home: {{ data['url'] }}
  summary: Wrapper to read fast5, slow5, blow5 and pod5 files.
  license: {{ data['license'] }}
  license_file: LICENSE
  doc_url: https://github.com/JannesSP/read5.github.io
  dev_url: {{ data['url'] }}

extra:
  recipe-maintainers:
    - 38325576